// Copyright 2022 Gravitational, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: v1/tshd_events_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReloginRequiredRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RootClusterUri string `protobuf:"bytes,1,opt,name=root_cluster_uri,json=rootClusterUri,proto3" json:"root_cluster_uri,omitempty"`
	// Types that are assignable to Reason:
	//
	//	*ReloginRequiredRequest_GatewayCertExpired
	Reason isReloginRequiredRequest_Reason `protobuf_oneof:"reason"`
}

func (x *ReloginRequiredRequest) Reset() {
	*x = ReloginRequiredRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_tshd_events_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloginRequiredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloginRequiredRequest) ProtoMessage() {}

func (x *ReloginRequiredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tshd_events_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloginRequiredRequest.ProtoReflect.Descriptor instead.
func (*ReloginRequiredRequest) Descriptor() ([]byte, []int) {
	return file_v1_tshd_events_service_proto_rawDescGZIP(), []int{0}
}

func (x *ReloginRequiredRequest) GetRootClusterUri() string {
	if x != nil {
		return x.RootClusterUri
	}
	return ""
}

func (m *ReloginRequiredRequest) GetReason() isReloginRequiredRequest_Reason {
	if m != nil {
		return m.Reason
	}
	return nil
}

func (x *ReloginRequiredRequest) GetGatewayCertExpired() *GatewayCertExpired {
	if x, ok := x.GetReason().(*ReloginRequiredRequest_GatewayCertExpired); ok {
		return x.GatewayCertExpired
	}
	return nil
}

type isReloginRequiredRequest_Reason interface {
	isReloginRequiredRequest_Reason()
}

type ReloginRequiredRequest_GatewayCertExpired struct {
	GatewayCertExpired *GatewayCertExpired `protobuf:"bytes,2,opt,name=gateway_cert_expired,json=gatewayCertExpired,proto3,oneof"`
}

func (*ReloginRequiredRequest_GatewayCertExpired) isReloginRequiredRequest_Reason() {}

type GatewayCertExpired struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GatewayUri string `protobuf:"bytes,1,opt,name=gateway_uri,json=gatewayUri,proto3" json:"gateway_uri,omitempty"`
	TargetUri  string `protobuf:"bytes,2,opt,name=target_uri,json=targetUri,proto3" json:"target_uri,omitempty"`
}

func (x *GatewayCertExpired) Reset() {
	*x = GatewayCertExpired{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_tshd_events_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayCertExpired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayCertExpired) ProtoMessage() {}

func (x *GatewayCertExpired) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tshd_events_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayCertExpired.ProtoReflect.Descriptor instead.
func (*GatewayCertExpired) Descriptor() ([]byte, []int) {
	return file_v1_tshd_events_service_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayCertExpired) GetGatewayUri() string {
	if x != nil {
		return x.GatewayUri
	}
	return ""
}

func (x *GatewayCertExpired) GetTargetUri() string {
	if x != nil {
		return x.TargetUri
	}
	return ""
}

type ReloginRequiredResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReloginRequiredResponse) Reset() {
	*x = ReloginRequiredResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_tshd_events_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloginRequiredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloginRequiredResponse) ProtoMessage() {}

func (x *ReloginRequiredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tshd_events_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloginRequiredResponse.ProtoReflect.Descriptor instead.
func (*ReloginRequiredResponse) Descriptor() ([]byte, []int) {
	return file_v1_tshd_events_service_proto_rawDescGZIP(), []int{2}
}

var File_v1_tshd_events_service_proto protoreflect.FileDescriptor

var file_v1_tshd_events_service_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x76, 0x31, 0x2f, 0x74, 0x73, 0x68, 0x64, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14,
	0x74, 0x65, 0x6c, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61,
	0x6c, 0x2e, 0x76, 0x31, 0x22, 0xaa, 0x01, 0x0a, 0x16, 0x52, 0x65, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x28, 0x0a, 0x10, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f,
	0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x6f, 0x6f, 0x74, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x55, 0x72, 0x69, 0x12, 0x5c, 0x0a, 0x14, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x5f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x43, 0x65, 0x72, 0x74, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x64, 0x48, 0x00, 0x52, 0x12, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x43, 0x65, 0x72, 0x74,
	0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x22, 0x54, 0x0a, 0x12, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x43, 0x65, 0x72, 0x74,
	0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x55, 0x72, 0x69, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x55, 0x72, 0x69, 0x22, 0x19, 0x0a, 0x17, 0x52, 0x65, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0x83, 0x01, 0x0a, 0x11, 0x54, 0x73, 0x68, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6e, 0x0a, 0x0f, 0x52, 0x65, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x12, 0x2c, 0x2e, 0x74, 0x65,
	0x6c, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x74, 0x65, 0x6c, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x72, 0x61, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x6c, 0x69,
	0x62, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x72, 0x6d, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_tshd_events_service_proto_rawDescOnce sync.Once
	file_v1_tshd_events_service_proto_rawDescData = file_v1_tshd_events_service_proto_rawDesc
)

func file_v1_tshd_events_service_proto_rawDescGZIP() []byte {
	file_v1_tshd_events_service_proto_rawDescOnce.Do(func() {
		file_v1_tshd_events_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_tshd_events_service_proto_rawDescData)
	})
	return file_v1_tshd_events_service_proto_rawDescData
}

var file_v1_tshd_events_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_tshd_events_service_proto_goTypes = []interface{}{
	(*ReloginRequiredRequest)(nil),  // 0: teleport.terminal.v1.ReloginRequiredRequest
	(*GatewayCertExpired)(nil),      // 1: teleport.terminal.v1.GatewayCertExpired
	(*ReloginRequiredResponse)(nil), // 2: teleport.terminal.v1.ReloginRequiredResponse
}
var file_v1_tshd_events_service_proto_depIdxs = []int32{
	1, // 0: teleport.terminal.v1.ReloginRequiredRequest.gateway_cert_expired:type_name -> teleport.terminal.v1.GatewayCertExpired
	0, // 1: teleport.terminal.v1.TshdEventsService.ReloginRequired:input_type -> teleport.terminal.v1.ReloginRequiredRequest
	2, // 2: teleport.terminal.v1.TshdEventsService.ReloginRequired:output_type -> teleport.terminal.v1.ReloginRequiredResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_tshd_events_service_proto_init() }
func file_v1_tshd_events_service_proto_init() {
	if File_v1_tshd_events_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_tshd_events_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReloginRequiredRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_tshd_events_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayCertExpired); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_tshd_events_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReloginRequiredResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v1_tshd_events_service_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ReloginRequiredRequest_GatewayCertExpired)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_tshd_events_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_tshd_events_service_proto_goTypes,
		DependencyIndexes: file_v1_tshd_events_service_proto_depIdxs,
		MessageInfos:      file_v1_tshd_events_service_proto_msgTypes,
	}.Build()
	File_v1_tshd_events_service_proto = out.File
	file_v1_tshd_events_service_proto_rawDesc = nil
	file_v1_tshd_events_service_proto_goTypes = nil
	file_v1_tshd_events_service_proto_depIdxs = nil
}
